### ISSUE TITLE
Workflows are referencing vulnerable actions

### ISSUE THREAD

**Issue by igibek** [ionixjunior/Xalendar#106]
Hello, there! 

As part of the university research we are currently doing regarding the security of Github Actions, we noticed that one or many of the workflows that are part of this repository are referencing vulnerable versions of the third-party actions. As part of a disclosure process, we decided to open issues to notify GitHub Community. 

*Please note that there are could be some false positives in our methodology, thus not all of the open issues could be valid. If that is the case, please let us know, so that we can improve on our approach. You can contact me directly using an email: ikoishy [at] ncsu.edu* 

Thanks in advance
1. The workflow **publish_package.yml** is referencing action **gittools/actions/gitversion/setup** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **publish_package.yml** is referencing action **gittools/actions/gitversion/execute** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **publish_package_pre_release.yml** is referencing action **gittools/actions/gitversion/setup** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **publish_package_pre_release.yml** is referencing action **gittools/actions/gitversion/execute** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.

The vulnerability fix that is missing by actions' versions could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider updating the reference to the action. 

*If you end up updating the reference, please let us know. We need the stats for the paper :-)*

**Comment by ionixjunior** [comment]
Hi @igibek! Thank you for your issue!

I forgot to specify the latest version of the gitversion script when I do this.

I saw the release notes of the gitversion script and, the main change was the migration to node 10, as you can see in this link https://github.com/GitTools/actions/releases. 

I changed the reference v0.9.7 to v0 in these scripts (merged into develop). I don't know if this is enough to solve the vulnerability that you found. Could you check again to see if there is another potential vulnerability?

Thank you for your time!

**Comment by ionixjunior** [comment]
I'm closing this issue. @igibek, if the problem persists, please reopen it. Thank you!
