### ISSUE TITLE
Select Multiple days

### ISSUE THREAD

**Issue by Lukas182** [ionixjunior/Xalendar#91]
Hello!

The plugin looks pretty nice! Welldone!

Is possible to have more than 1 day selected on the calendar?

Thanks!

Regards,

David

**Comment by ionixjunior** [comment]
Hello, @Lukas182! 

Thank you so much!

Currently, only a single selection is supported, but this is an interesting thing to do. 

Would you like to share with me a specification about this?

**Comment by Lukas182** [comment]
Hey @ionixjunior 

Sure! The main idea is to keep as "selected" all days that you touch on the calendar and not just the last one. I guess you will need to add a List to keep them on track and add a function to access all the selected days and not only the last one. 

Meanwhile it isn't supported, Im doing the same and adding them on a list and removing them if I touch one that was selected before but I would like to have them highlighted as "selected" on calendar.

![Captura de pantalla 2021-05-12 a las 8 19 04](https://user-images.githubusercontent.com/5369988/117927651-c749c200-b2fa-11eb-957c-3ee0d31d1238.png)

Also.. another awesome feature would be to make some days disabled ( not selectable ). I mean.. let's suppose I only want that the user interact with the days of the current week or only with the days of the current month or something like that.

Thanks for your time! :)

**Comment by ionixjunior** [comment]
Hi, @Lukas182. Thank you for your explanation. 

Well, this is not a hard thing to do. I'll put this in the backlog and think about an implementation in the next few days.

About the disabled days, this is already in the backlog, but I didn't develop yet - Restrict a date interval to interact https://github.com/ionixjunior/Xalendar/projects/1

**Comment by Lukas182** [comment]
Cool mate!
 
Keep me updated when you have done those features! :D

**Comment by ionixjunior** [comment]
@Lukas182 I'm working on it, but I haven't finished it yet. I'm solving some issues that I found. In my next free time (probably the next weekend), I'll finish this feature.

**Comment by Lukas182** [comment]
@ionixjunior thanks mate! looks pretty nice! :)

**Comment by ionixjunior** [comment]
@Lukas182 can you check [this pull request](https://github.com/ionixjunior/Xalendar/pull/92) to validate the multi-select support, please? The package is not published before the merge, so you will need to checkout the pull request branch to check it.

**Comment by Lukas182** [comment]
Sure mate, ill try to do it asap , bit busy this days!
